export { default as About } from './About/About'
export {default as Home} from './Home/Home'
export {default as Login} from './Login/Login'
export {default as MovieDetails} from './MovieDetails/MovieDetails'
export {default as TvDetails} from './MovieDetails/TvDetails'
export {default as PersonDetails} from './MovieDetails/PersonDetails'
export {default as Movies} from './Movies/Movies'
export {default as Navbar} from './Navbar/Navbar'
export {default as People} from './People/People'
export {default as Tvshow} from './Tvshow/Tvshow'
export {default as Notfound} from './Notfound/Notfound'
export {default as Layout} from './Layout/Layout'
export {default as Register} from './Register/Register'
export {default as ContactForm} from './ContactForm/ContactForm'